output-reports:
  active: false
complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 20
    ignoreDefaultParameters: true
naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    active: true
    propertyPattern: '[a-zA-Z][a-zA-Z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-zA-Z_$]*)*'
style:
  active: true
  MagicNumber:
    active: true
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
  MaxLineLength:
    excludeCommentStatements: true
  ForbiddenComment:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview', 'Test']
  UnusedImports:
    active: true
  NewLineAtEndOfFile:
    active: false